import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';
import { NextAuthProvider } from "@/registry/new-york/blocks/session-provider/session-provider";
import { ThemeProvider } from "@/registry/new-york/blocks/theme-provider/theme-provider";
import { Header } from "@/registry/new-york/blocks/header/header";
import { Content } from "@/registry/new-york/blocks/content/content";
import Sidebar from "@/registry/new-york/blocks/sidebar/sidebar";
import { SidebarInset, SidebarProvider } from "@/registry/new-york/ui/sidebar";
import { LayoutGrid } from "lucide-react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headerMenu = {
  icon: LayoutGrid,
  title: "App Name",
  subtitle: "v1alpha1",
  href: "/app"
}

const navItems = [
  {
    name: "Resource Category",
    href: "/app",
    items: [
      { name: "Home", href: "/app" },
      { name: "Resource Type 1", href: "/app/resource1" },
      { name: "Resource Type 2", href: "/app/resource2" }
    ]
  }
];


export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();

  return (
    <html lang={locale} >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <NextIntlClientProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <SidebarProvider>
                <Sidebar headerMenu={headerMenu} navItems={navItems} />
                <SidebarInset>
                  <Header />
                  <Content>
                    <div className="flex">
                      <main className="flex-1">
                        {children}
                      </main>
                    </div>
                  </Content>
                </SidebarInset>
              </SidebarProvider>
            </ThemeProvider>
          </NextIntlClientProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}