name: Registry Build

on:
  push:
    branches: ["main", "master"]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "package.json"

jobs:
  build:
    name: Build Registry
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build registry
        run: pnpm registry:build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: registry build [skip ci]"
          branch: ${{ github.ref_name }}
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
          file_pattern: 'public/r/*.json pnpm-lock.yaml'
